#!/bin/bash

mkdir -p output_gen/


generar_archivo() {
    echo "Generando archivo de $tipo_aleatorio..."
    tipo=("imagen" "sonido" "texto")
    cantidad=${#tipo[@]}
    fiumba=$((RANDOM % $cantidad))
    tucu=${tipo[$fiumba]}
    echo $tucu

    case $tucu in
	texto)
            base64 /dev/urandom | head -c 500 > "output_gen/texto"
	      pum=$(md5sum "output_gen/texto" | cut -d " " -f1)
   	      mv "output_gen/texto" "./output_gen/$pum"
              ;;
        sonido)
            ffmpeg -f lavfi -i "anoisesrc=a=0.1:c=white:duration=5" "output_gen/out.wav" 
	     pum=$(md5sum "output_gen/out.wav" | cut -d " " -f1)
   	     mv "output_gen/out.wav" "./output_gen/$pum"
             ;;
        imagen)
            convert -size 100x100 xc: +noise Random  "output_gen/imagen.png"
	     pum=$(md5sum "output_gen/imagen.png" | cut -d " " -f1)
   	     mv "output_gen/imagen.png" "./output_gen/$pum" 
             ;;
        *)
            echo "Tipo de archivo no válido."
            return 1
            ;;
    esac
}

generar_archivo 




